### PR TITLE
Decaffeinate stripe_donation.js.coffee

### PR DESCRIPTION
**Pull request by texpert**

### CODE REVIEW

**Comment by texpert** [comment]
@owen2345, please, have a look at this!

**Review by owen2345 — APPROVED** [review]
LGTM.

**Comment by owen2345** [comment]
@texpert IMO you should ignore the pages/sections/features not related to the gem itself. Just keep the documentation and perhaps the home page.
What do u think?

**Comment by texpert** [comment]
@owen2345, I think it is tougher to remove embedded functionality than just converting CoffeeScript to JS :)

Can you, please, merge this and cut a new release?!

**Review by owen2345 — APPROVED** [review]
LGTM

**Comment by texpert** [comment]
@owen2345, thanks for approving!

Can you, please, merge it?! I have no rights to merge.

**Comment by owen2345** [comment]
> @owen2345, thanks for approving!
> 
> Can you, please, merge it?! I have no rights to merge.

Added you as collaborator

**Pull request merged**
